// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEsKZq3QgqVuAIWvrn-5uuJsElzXPMQjg',
    appId: '1:819631877981:web:b6c5994304e9b6981d42b4',
    messagingSenderId: '819631877981',
    projectId: 'cred-vault-6bf20',
    authDomain: 'cred-vault-6bf20.firebaseapp.com',
    storageBucket: 'cred-vault-6bf20.firebasestorage.app',
    measurementId: 'G-3YS3DNRFFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6O2axgPutyOHMDV358FZOv_NXi5NIFA',
    appId: '1:819631877981:android:6c579339ea54a5351d42b4',
    messagingSenderId: '819631877981',
    projectId: 'cred-vault-6bf20',
    storageBucket: 'cred-vault-6bf20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrFjuDw-KHWZRkJERtQl8augdq1cQN-Y4',
    appId: '1:819631877981:ios:038b77798bb08ee11d42b4',
    messagingSenderId: '819631877981',
    projectId: 'cred-vault-6bf20',
    storageBucket: 'cred-vault-6bf20.firebasestorage.app',
    iosBundleId: 'com.example.credVault',
  );
}
